### ISSUE TITLE
Adjust CSS for desktop screen view for attendance statistics => student dashboard

### ISSUE THREAD

**Issue by hr097** [hr097/JAMES#11]
Please take care of mobile view.

![image](https://user-images.githubusercontent.com/82766099/195373141-422103e9-0aa1-4f41-a2d7-f339cdbacc56.png)

**Comment by Acaashmi** [comment]
hi, i would love to work on this project.......please assign me

**Comment by hr097** [comment]
Kindly drop your WhatsApp number and let’s get know each other.

Regards,
Team leader.
(project JAMES)
